### ISSUE TITLE
ZStack & GCVirtualController

### ISSUE THREAD

**Issue by gentique** [damikdk/SwiftUI-Games#4]
Hi 👋 ,

Thanks for providing these samples! 
I'm in a similar situation as to a comment in your code 
```
    // ZStack it is just a bad workaround for GCVirtualController.
    // Earlier I used `fullScreenCover`, but GCVirtualController appears BELOW it.
    // So keep GCVirtualController in View, not Overlay/Modal/Sheet containers
```

How come none have mentioned this issue? There's literally no post related to this. Have you discovered anything new in the meantime? 

Thanks in advance!

**Comment by damikdk** [comment]
Hello, @gentique. I will try something on this weekend, stay tuned. 

But I am sure that this bug will be with us for at least a couple of years. SwiftUI is raw by itself, so rare and non-obvious components like GCVirtualController staying forgotten for years

**Comment by damikdk** [comment]
@gentique I didn't find any good solutions. So we will wait for Apple

**Comment by damikdk** [comment]
I'm not sure what exactly we want. 

Probably the ideal option for Apple would be to make something like `GCVirtualControllerView` that would behave like a `View` and could be located anywhere. In this case, they can even embed the logic of creating a controller and connect/disconnect methods inside this `GCVirtualControllerView`.

But since it now works magically and appears wherever it wants, there is no way to fix it, it will be strange to use anyway. So I'm rather waiting not for the correction of this non-obviousness, but for a complete **rework**.

https://openradar.appspot.com/search?query=GCVirtualController
